/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class springWeb_controller_HelloWorld */

#ifndef _Included_springWeb_controller_HelloWorld
#define _Included_springWeb_controller_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     springWeb_controller_HelloWorld
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_springWeb_controller_HelloWorld_test
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL JNI_OnLoad( JavaVM *, void *);
JNIEXPORT void JNICALL JNI_OnUnload( JavaVM *, void *);
#ifdef __cplusplus
}
#endif
#endif
