package springWeb.airTicket.response;

import com.fasterxml.jackson.dataformat.xml.XmlMapper;
import org.junit.Test;
import springWeb.airTicket.response.model.AirLine;
import springWeb.airTicket.response.model.TicketQueryResponse;
import springWeb.util.XmlParser;

import java.io.*;
import java.util.List;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;
import static org.junit.Assert.assertThat;

public class XmlParserTest {
    @Test
    public void should_parse_ticket_response() throws IOException {
        XmlMapper xmlMapper = new XmlMapper();
//        TicketQueryResponse ticketQueryResponse = xmlMapper.readValue("/Users/twer/homeideas/Spring-Session/springWeb/src/test/resources/reponse.xml", TicketQueryResponse.class);
        XmlParser parser = new XmlParser<TicketQueryResponse>();
        String content = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<FlightSearchReply xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n" +
                "    <ExtensionData/>\n" +
                "    <ExcuteNormal>true</ExcuteNormal>\n" +
                "    <ReturnCode>Y</ReturnCode>\n" +
                "    <ReturnMessage>成功查询</ReturnMessage>\n" +
                "    <LinesCollection>\n" +
                "        <Lines>\n" +
                "            <ExtensionData/>\n" +
                "            <AirItems>\n" +
                "                <AirItem>\n" +
                "                    <ExtensionData/>\n" +
                "                    <Airline>HO</Airline>\n" +
                "                    <AirportTax>50</AirportTax>\n" +
                "                    <BasePrice>1130</BasePrice>\n" +
                "                    <Cabins>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>3050</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>F</CabinType>\n" +
                "                            <ChildiePrice>1530</ChildiePrice>\n" +
                "                            <Code>F</Code>\n" +
                "                            <CommissionHistoryId>1851750053</CommissionHistoryId>\n" +
                "                            <DiscountRate>270</DiscountRate>\n" +
                "                            <DiscountRateExp>100</DiscountRateExp>\n" +
                "                            <InfantPrice>310</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>8</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>7</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>900.0000</AdultPrice>\n" +
                "                            <CabinDesc>80</CabinDesc>\n" +
                "                            <CabinType>F</CabinType>\n" +
                "                            <ChildiePrice>1530</ChildiePrice>\n" +
                "                            <Code>A</Code>\n" +
                "                            <CommissionHistoryId>1227555000</CommissionHistoryId>\n" +
                "                            <DiscountRate>80</DiscountRate>\n" +
                "                            <DiscountRateExp>30</DiscountRateExp>\n" +
                "                            <InfantPrice>310</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>4</Number>\n" +
                "                            <PolicyType>2</PolicyType>\n" +
                "                            <RebateRate>3</RebateRate>\n" +
                "                            <Remark>\n" +
                "                                &lt;超值头等舱&gt;地面、空中均享受头等舱服务；上海两场专用摆渡车；登机时享受随时登机便利通道；免费行李额增加至40KG。&lt;/超值头等舱&gt;</Remark>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>1914090</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>1130</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>Y</Code>\n" +
                "                            <CommissionHistoryId>-1919631266</CommissionHistoryId>\n" +
                "                            <DiscountRate>100</DiscountRate>\n" +
                "                            <DiscountRateExp>100</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>6</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>1020</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>B</Code>\n" +
                "                            <CommissionHistoryId>-1919631266</CommissionHistoryId>\n" +
                "                            <DiscountRate>90</DiscountRate>\n" +
                "                            <DiscountRateExp>90</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>6</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>960</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>L</Code>\n" +
                "                            <CommissionHistoryId>-1919631266</CommissionHistoryId>\n" +
                "                            <DiscountRate>85</DiscountRate>\n" +
                "                            <DiscountRateExp>85</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>6</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>900</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>M</Code>\n" +
                "                            <CommissionHistoryId>-1919631266</CommissionHistoryId>\n" +
                "                            <DiscountRate>80</DiscountRate>\n" +
                "                            <DiscountRateExp>80</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>6</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>850</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>T</Code>\n" +
                "                            <CommissionHistoryId>-1919631266</CommissionHistoryId>\n" +
                "                            <DiscountRate>75</DiscountRate>\n" +
                "                            <DiscountRateExp>75</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>6</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>790</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>E</Code>\n" +
                "                            <CommissionHistoryId>-1919631266</CommissionHistoryId>\n" +
                "                            <DiscountRate>70</DiscountRate>\n" +
                "                            <DiscountRateExp>70</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>6</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>730</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>H</Code>\n" +
                "                            <CommissionHistoryId>-1919631266</CommissionHistoryId>\n" +
                "                            <DiscountRate>65</DiscountRate>\n" +
                "                            <DiscountRateExp>65</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>6</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>680</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>V</Code>\n" +
                "                            <CommissionHistoryId>-1919631266</CommissionHistoryId>\n" +
                "                            <DiscountRate>60</DiscountRate>\n" +
                "                            <DiscountRateExp>60</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>6</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>620</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>K</Code>\n" +
                "                            <CommissionHistoryId>-1919631266</CommissionHistoryId>\n" +
                "                            <DiscountRate>55</DiscountRate>\n" +
                "                            <DiscountRateExp>55</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>6</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>570</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>W</Code>\n" +
                "                            <CommissionHistoryId>-1919631266</CommissionHistoryId>\n" +
                "                            <DiscountRate>50</DiscountRate>\n" +
                "                            <DiscountRateExp>50</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>6</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>510</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>R</Code>\n" +
                "                            <CommissionHistoryId>-1919631266</CommissionHistoryId>\n" +
                "                            <DiscountRate>45</DiscountRate>\n" +
                "                            <DiscountRateExp>45</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>6</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>450</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>Q</Code>\n" +
                "                            <CommissionHistoryId>-1919631266</CommissionHistoryId>\n" +
                "                            <DiscountRate>40</DiscountRate>\n" +
                "                            <DiscountRateExp>40</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>6</RebateRate>\n" +
                "                            <Remark/>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>380.0000</AdultPrice>\n" +
                "                            <CabinDesc>34</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>X</Code>\n" +
                "                            <CommissionHistoryId>1227555000</CommissionHistoryId>\n" +
                "                            <DiscountRate>34</DiscountRate>\n" +
                "                            <DiscountRateExp>34</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>2</PolicyType>\n" +
                "                            <RebateRate>3</RebateRate>\n" +
                "                            <Remark/>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>1914087</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                    </Cabins>\n" +
                "                    <CodeShare>false</CodeShare>\n" +
                "                    <DelayPercent>96.67</DelayPercent>\n" +
                "                    <Distance>0</Distance>\n" +
                "                    <DstAirport>SHA</DstAirport>\n" +
                "                    <DstDateTime>2012-11-03T08:45:00</DstDateTime>\n" +
                "                    <DstTerm>T2</DstTerm>\n" +
                "                    <FlightId>1</FlightId>\n" +
                "                    <FlightNo>HO1252</FlightNo>\n" +
                "                    <FuelTax>140</FuelTax>\n" +
                "                    <HasMeal>true</HasMeal>\n" +
                "                    <IsETkt>true</IsETkt>\n" +
                "                    <MealCode>B</MealCode>\n" +
                "                    <NextFlightId>0</NextFlightId>\n" +
                "                    <NoneDirectLine>false</NoneDirectLine>\n" +
                "                    <OpenCabinsCode>F,A,Y,B,L,M,T,E,H,V,K,W,R,Q,Z,X,G,S,I,</OpenCabinsCode>\n" +
                "                    <OrgAirport>PEK</OrgAirport>\n" +
                "                    <OrgDateTime>2012-11-03T06:35:00</OrgDateTime>\n" +
                "                    <OrgTerm>T3</OrgTerm>\n" +
                "                    <PlaneStyle>320</PlaneStyle>\n" +
                "                    <StopNumber>0</StopNumber>\n" +
                "                </AirItem>\n" +
                "                <AirItem>\n" +
                "                    <ExtensionData/>\n" +
                "                    <Airline>CA</Airline>\n" +
                "                    <AirportTax>50</AirportTax>\n" +
                "                    <BasePrice>1130</BasePrice>\n" +
                "                    <Cabins>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>3390</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>F</CabinType>\n" +
                "                            <ChildiePrice>1580</ChildiePrice>\n" +
                "                            <Code>P</Code>\n" +
                "                            <CommissionHistoryId>-730429281</CommissionHistoryId>\n" +
                "                            <DiscountRate>300</DiscountRate>\n" +
                "                            <DiscountRateExp>107</DiscountRateExp>\n" +
                "                            <InfantPrice>320</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>7</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>3.3</RebateRate>\n" +
                "                            <Remark/>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>3160</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>F</CabinType>\n" +
                "                            <ChildiePrice>1580</ChildiePrice>\n" +
                "                            <Code>F</Code>\n" +
                "                            <CommissionHistoryId>-730429281</CommissionHistoryId>\n" +
                "                            <DiscountRate>280</DiscountRate>\n" +
                "                            <DiscountRateExp>100</DiscountRateExp>\n" +
                "                            <InfantPrice>320</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>3.3</RebateRate>\n" +
                "                            <Remark/>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>2830</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>F</CabinType>\n" +
                "                            <ChildiePrice>1580</ChildiePrice>\n" +
                "                            <Code>A</Code>\n" +
                "                            <CommissionHistoryId>-730429281</CommissionHistoryId>\n" +
                "                            <DiscountRate>250</DiscountRate>\n" +
                "                            <DiscountRateExp>90</DiscountRateExp>\n" +
                "                            <InfantPrice>320</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>3.3</RebateRate>\n" +
                "                            <Remark/>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>1130</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>Y</Code>\n" +
                "                            <CommissionHistoryId>-730429281</CommissionHistoryId>\n" +
                "                            <DiscountRate>100</DiscountRate>\n" +
                "                            <DiscountRateExp>100</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>3.3</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>1020</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>B</Code>\n" +
                "                            <CommissionHistoryId>-730429281</CommissionHistoryId>\n" +
                "                            <DiscountRate>90</DiscountRate>\n" +
                "                            <DiscountRateExp>90</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>3.3</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>990</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>M</Code>\n" +
                "                            <CommissionHistoryId>-730429281</CommissionHistoryId>\n" +
                "                            <DiscountRate>88</DiscountRate>\n" +
                "                            <DiscountRateExp>88</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>3.3</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                            <SubCabins>\n" +
                "                                <SubCabin>\n" +
                "                                    <ExtensionData/>\n" +
                "                                    <Code>M1</Code>\n" +
                "                                    <CommissionHistoryId>1275228000</CommissionHistoryId>\n" +
                "                                    <DiscountRate>85</DiscountRate>\n" +
                "                                    <DiscountRateExp>85</DiscountRateExp>\n" +
                "                                    <Number>10</Number>\n" +
                "                                    <Price>960</Price>\n" +
                "                                    <RebateRate>3</RebateRate>\n" +
                "                                </SubCabin>\n" +
                "                            </SubCabins>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>900</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>H</Code>\n" +
                "                            <CommissionHistoryId>-730429281</CommissionHistoryId>\n" +
                "                            <DiscountRate>80</DiscountRate>\n" +
                "                            <DiscountRateExp>80</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>3.3</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>850</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>K</Code>\n" +
                "                            <CommissionHistoryId>-730429281</CommissionHistoryId>\n" +
                "                            <DiscountRate>75</DiscountRate>\n" +
                "                            <DiscountRateExp>75</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>3.3</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>790</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>L</Code>\n" +
                "                            <CommissionHistoryId>-730429281</CommissionHistoryId>\n" +
                "                            <DiscountRate>70</DiscountRate>\n" +
                "                            <DiscountRateExp>70</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>3.3</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>680</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>Q</Code>\n" +
                "                            <CommissionHistoryId>-730429281</CommissionHistoryId>\n" +
                "                            <DiscountRate>60</DiscountRate>\n" +
                "                            <DiscountRateExp>60</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>3.3</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>570</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>G</Code>\n" +
                "                            <CommissionHistoryId>-730429281</CommissionHistoryId>\n" +
                "                            <DiscountRate>50</DiscountRate>\n" +
                "                            <DiscountRateExp>50</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>3.3</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>450.0000</AdultPrice>\n" +
                "                            <CabinDesc>40</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>E</Code>\n" +
                "                            <CommissionHistoryId>1275228000</CommissionHistoryId>\n" +
                "                            <DiscountRate>40</DiscountRate>\n" +
                "                            <DiscountRateExp>40</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>7</Number>\n" +
                "                            <PolicyType>2</PolicyType>\n" +
                "                            <RebateRate>3</RebateRate>\n" +
                "                            <Remark/>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>1864903</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>960.0000</AdultPrice>\n" +
                "                            <CabinDesc>85</CabinDesc>\n" +
                "                            <CabinType>F</CabinType>\n" +
                "                            <ChildiePrice>1580</ChildiePrice>\n" +
                "                            <Code>A</Code>\n" +
                "                            <CommissionHistoryId>-730429281</CommissionHistoryId>\n" +
                "                            <DiscountRate>85</DiscountRate>\n" +
                "                            <DiscountRateExp>30</DiscountRateExp>\n" +
                "                            <InfantPrice>320</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>2</PolicyType>\n" +
                "                            <RebateRate>3.3</RebateRate>\n" +
                "                            <Remark>&lt;超值产品&gt;1、机上百分百头等舱专属餐食、饮料、服务等尊贵享受。2、独立的机上娱乐系统。3、头等舱专属柜台办理乘机手续优先登机并有全新装修国航自营休息室。4、行李额40公斤，按200％的比例累积里程。&lt;/超值产品&gt;</Remark>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>1864898</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>2490.0000</AdultPrice>\n" +
                "                            <CabinDesc>220</CabinDesc>\n" +
                "                            <CabinType>F</CabinType>\n" +
                "                            <ChildiePrice>1580</ChildiePrice>\n" +
                "                            <Code>A</Code>\n" +
                "                            <CommissionHistoryId>-730429281</CommissionHistoryId>\n" +
                "                            <DiscountRate>220</DiscountRate>\n" +
                "                            <DiscountRateExp>79</DiscountRateExp>\n" +
                "                            <InfantPrice>320</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>2</PolicyType>\n" +
                "                            <RebateRate>3.3</RebateRate>\n" +
                "                            <Remark>&lt;超值产品&gt;1、机上百分百头等舱专属餐食、饮料、服务等尊贵享受。2、独立的机上娱乐系统。3、头等舱专属柜台办理乘机手续优先登机并有全新装修国航自营休息室。4、行李额40公斤，按200％的比例累积里程。&lt;/超值产品&gt;</Remark>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>1864900</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>680.0000</AdultPrice>\n" +
                "                            <CabinDesc>60</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>E</Code>\n" +
                "                            <CommissionHistoryId>1275228000</CommissionHistoryId>\n" +
                "                            <DiscountRate>60</DiscountRate>\n" +
                "                            <DiscountRateExp>60</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>7</Number>\n" +
                "                            <PolicyType>2</PolicyType>\n" +
                "                            <RebateRate>3</RebateRate>\n" +
                "                            <Remark/>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>1864905</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                    </Cabins>\n" +
                "                    <CodeShare>false</CodeShare>\n" +
                "                    <DelayPercent>96.15</DelayPercent>\n" +
                "                    <Distance>0</Distance>\n" +
                "                    <DstAirport>SHA</DstAirport>\n" +
                "                    <DstDateTime>2012-11-03T09:40:00</DstDateTime>\n" +
                "                    <DstTerm>T2</DstTerm>\n" +
                "                    <FlightId>3</FlightId>\n" +
                "                    <FlightNo>CA1831</FlightNo>\n" +
                "                    <FuelTax>140</FuelTax>\n" +
                "                    <HasMeal>true</HasMeal>\n" +
                "                    <IsETkt>true</IsETkt>\n" +
                "                    <MealCode>B</MealCode>\n" +
                "                    <NextFlightId>0</NextFlightId>\n" +
                "                    <NoneDirectLine>false</NoneDirectLine>\n" +
                "                    <OpenCabinsCode>P,F,A,Y,B,M,M1,H,K,L,Q,G,S,T,E,</OpenCabinsCode>\n" +
                "                    <OrgAirport>PEK</OrgAirport>\n" +
                "                    <OrgDateTime>2012-11-03T07:30:00</OrgDateTime>\n" +
                "                    <OrgTerm>T3</OrgTerm>\n" +
                "                    <PlaneStyle>773</PlaneStyle>\n" +
                "                    <StopNumber>0</StopNumber>\n" +
                "                </AirItem>\n" +
                "                <AirItem>\n" +
                "                    <ExtensionData/>\n" +
                "                    <Airline>FM</Airline>\n" +
                "                    <AirportTax>50</AirportTax>\n" +
                "                    <BasePrice>1130</BasePrice>\n" +
                "                    <Cabins>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>3160</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>F</CabinType>\n" +
                "                            <ChildiePrice>1580</ChildiePrice>\n" +
                "                            <Code>F</Code>\n" +
                "                            <CommissionHistoryId>-812888295</CommissionHistoryId>\n" +
                "                            <DiscountRate>280</DiscountRate>\n" +
                "                            <DiscountRateExp>100</DiscountRateExp>\n" +
                "                            <InfantPrice>320</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>4.8</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>990.0000</AdultPrice>\n" +
                "                            <CabinDesc>88</CabinDesc>\n" +
                "                            <CabinType>F</CabinType>\n" +
                "                            <ChildiePrice>1580</ChildiePrice>\n" +
                "                            <Code>P</Code>\n" +
                "                            <CommissionHistoryId>1227333000</CommissionHistoryId>\n" +
                "                            <DiscountRate>88</DiscountRate>\n" +
                "                            <DiscountRateExp>31</DiscountRateExp>\n" +
                "                            <InfantPrice>320</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>2</PolicyType>\n" +
                "                            <RebateRate>3</RebateRate>\n" +
                "                            <Remark>\n" +
                "                                &lt;超值产品&gt;1、头等舱的待遇，经济舱的价格，不享受头等舱安检通道；；2、儿童、婴儿不允许预订;3、价格以实际预订为准。&lt;/超值产品&gt;</Remark>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>1938417</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>1130</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>Y</Code>\n" +
                "                            <CommissionHistoryId>-812888295</CommissionHistoryId>\n" +
                "                            <DiscountRate>100</DiscountRate>\n" +
                "                            <DiscountRateExp>100</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>4.8</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>1070</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>B</Code>\n" +
                "                            <CommissionHistoryId>-812888295</CommissionHistoryId>\n" +
                "                            <DiscountRate>95</DiscountRate>\n" +
                "                            <DiscountRateExp>95</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>4.8</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>1020</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>E</Code>\n" +
                "                            <CommissionHistoryId>-812888295</CommissionHistoryId>\n" +
                "                            <DiscountRate>90</DiscountRate>\n" +
                "                            <DiscountRateExp>90</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>4.8</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>960</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>H</Code>\n" +
                "                            <CommissionHistoryId>-812888295</CommissionHistoryId>\n" +
                "                            <DiscountRate>85</DiscountRate>\n" +
                "                            <DiscountRateExp>85</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>4.8</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>920</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>L</Code>\n" +
                "                            <CommissionHistoryId>-812888295</CommissionHistoryId>\n" +
                "                            <DiscountRate>81</DiscountRate>\n" +
                "                            <DiscountRateExp>81</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>4.8</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>870</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>M</Code>\n" +
                "                            <CommissionHistoryId>-812888295</CommissionHistoryId>\n" +
                "                            <DiscountRate>77</DiscountRate>\n" +
                "                            <DiscountRateExp>77</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>4.8</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>820</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>N</Code>\n" +
                "                            <CommissionHistoryId>-812888295</CommissionHistoryId>\n" +
                "                            <DiscountRate>73</DiscountRate>\n" +
                "                            <DiscountRateExp>73</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>4.8</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>780</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>R</Code>\n" +
                "                            <CommissionHistoryId>-812888295</CommissionHistoryId>\n" +
                "                            <DiscountRate>69</DiscountRate>\n" +
                "                            <DiscountRateExp>69</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>4.8</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>730</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>S</Code>\n" +
                "                            <CommissionHistoryId>-812888295</CommissionHistoryId>\n" +
                "                            <DiscountRate>65</DiscountRate>\n" +
                "                            <DiscountRateExp>65</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>4.8</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>680</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>V</Code>\n" +
                "                            <CommissionHistoryId>-812888295</CommissionHistoryId>\n" +
                "                            <DiscountRate>60</DiscountRate>\n" +
                "                            <DiscountRateExp>60</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>4.8</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>570</AdultPrice>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>T</Code>\n" +
                "                            <CommissionHistoryId>-812888295</CommissionHistoryId>\n" +
                "                            <DiscountRate>50</DiscountRate>\n" +
                "                            <DiscountRateExp>50</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>4.8</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>510.0000</AdultPrice>\n" +
                "                            <CabinDesc>45</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>570</ChildiePrice>\n" +
                "                            <Code>X</Code>\n" +
                "                            <CommissionHistoryId>1275289000</CommissionHistoryId>\n" +
                "                            <DiscountRate>45</DiscountRate>\n" +
                "                            <DiscountRateExp>45</DiscountRateExp>\n" +
                "                            <InfantPrice>110</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>2</PolicyType>\n" +
                "                            <RebateRate>3</RebateRate>\n" +
                "                            <Remark/>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>1975968</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                    </Cabins>\n" +
                "                    <CodeShare>false</CodeShare>\n" +
                "                    <DelayPercent>82.76</DelayPercent>\n" +
                "                    <Distance>0</Distance>\n" +
                "                    <DstAirport>SHA</DstAirport>\n" +
                "                    <DstDateTime>2012-11-03T09:45:00</DstDateTime>\n" +
                "                    <DstTerm>T2</DstTerm>\n" +
                "                    <FlightId>4</FlightId>\n" +
                "                    <FlightNo>FM9108</FlightNo>\n" +
                "                    <FuelTax>140</FuelTax>\n" +
                "                    <HasMeal>true</HasMeal>\n" +
                "                    <IsETkt>true</IsETkt>\n" +
                "                    <MealCode>S</MealCode>\n" +
                "                    <NextFlightId>0</NextFlightId>\n" +
                "                    <NoneDirectLine>false</NoneDirectLine>\n" +
                "                    <OpenCabinsCode>F,P,A,Y,K,B,E,H,L,M,N,R,S,V,T,X,Q,I,</OpenCabinsCode>\n" +
                "                    <OrgAirport>PEK</OrgAirport>\n" +
                "                    <OrgDateTime>2012-11-03T07:35:00</OrgDateTime>\n" +
                "                    <OrgTerm>T2</OrgTerm>\n" +
                "                    <PlaneStyle>75B</PlaneStyle>\n" +
                "                    <StopNumber>0</StopNumber>\n" +
                "                </AirItem>\n" +
                "            </AirItems>\n" +
                "            <Distance>1178</Distance>\n" +
                "            <DstCity>SHA</DstCity>\n" +
                "            <OrgCity>PEK</OrgCity>\n" +
                "            <OrgDate>2012-11-03T00:00:00</OrgDate>\n" +
                "        </Lines>\n" +
                "    </LinesCollection>\n" +
                "</FlightSearchReply>";
        TicketQueryResponse ticketQueryResponse = (TicketQueryResponse) parser.parse(content, TicketQueryResponse.class);
//        TicketQueryResponse ticketQueryResponse = xmlMapper.readValue(content, TicketQueryResponse.class);
        List<AirLine> airLines = ticketQueryResponse.getLinesCollection().getLines().getAirLines();
        assertThat(airLines, notNullValue());
        assertThat(airLines.get(0).getAirportTax(), is("50"));
        assertThat(airLines.get(0).getCabins().get(0).getAdultPrice(), is("3050"));
    }

    @Test
    public void should_parse_ticket_with_one_airline_response() throws IOException {
        XmlMapper xmlMapper = new XmlMapper();
//        TicketQueryResponse ticketQueryResponse = xmlMapper.readValue("/Users/twer/homeideas/Spring-Session/springWeb/src/test/resources/reponse.xml", TicketQueryResponse.class);
        XmlParser parser = new XmlParser<TicketQueryResponse>();
        String content = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n" +
                "<FlightSearchReply xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n" +
                "    <ExtensionData/>\n" +
                "    <ExcuteNormal>true</ExcuteNormal>\n" +
                "    <ReturnCode>Y</ReturnCode>\n" +
                "    <ReturnMessage>成功查询</ReturnMessage>\n" +
                "    <LinesCollection>\n" +
                "        <Lines>\n" +
                "            <ExtensionData/>\n" +
                "            <AirItems>\n" +
                "                <AirItem>\n" +
                "                    <ExtensionData/>\n" +
                "                    <AirItemAttr/>\n" +
                "                    <Airline>MU</Airline>\n" +
                "                    <AirportTax>50</AirportTax>\n" +
                "                    <BasePrice>1650</BasePrice>\n" +
                "                    <Cabins>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>4620</AdultPrice>\n" +
                "                            <CabinAttr/>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>F</CabinType>\n" +
                "                            <ChildiePrice>2310</ChildiePrice>\n" +
                "                            <Code>F</Code>\n" +
                "                            <CommissionHistoryId>1679695708</CommissionHistoryId>\n" +
                "                            <DiscountRate>280</DiscountRate>\n" +
                "                            <DiscountRateExp>100</DiscountRateExp>\n" +
                "                            <InfantPrice>460</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>8</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>4</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>1650</AdultPrice>\n" +
                "                            <CabinAttr/>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>830</ChildiePrice>\n" +
                "                            <Code>Y</Code>\n" +
                "                            <CommissionHistoryId>1679695708</CommissionHistoryId>\n" +
                "                            <DiscountRate>100</DiscountRate>\n" +
                "                            <DiscountRateExp>100</DiscountRateExp>\n" +
                "                            <InfantPrice>170</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>4</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>1490</AdultPrice>\n" +
                "                            <CabinAttr/>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>830</ChildiePrice>\n" +
                "                            <Code>B</Code>\n" +
                "                            <CommissionHistoryId>1679695708</CommissionHistoryId>\n" +
                "                            <DiscountRate>90</DiscountRate>\n" +
                "                            <DiscountRateExp>90</DiscountRateExp>\n" +
                "                            <InfantPrice>170</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>5</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>4</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>1400</AdultPrice>\n" +
                "                            <CabinAttr/>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>830</ChildiePrice>\n" +
                "                            <Code>E</Code>\n" +
                "                            <CommissionHistoryId>1679695708</CommissionHistoryId>\n" +
                "                            <DiscountRate>85</DiscountRate>\n" +
                "                            <DiscountRateExp>85</DiscountRateExp>\n" +
                "                            <InfantPrice>170</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>5</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>4</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>1320</AdultPrice>\n" +
                "                            <CabinAttr/>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>830</ChildiePrice>\n" +
                "                            <Code>H</Code>\n" +
                "                            <CommissionHistoryId>1679695708</CommissionHistoryId>\n" +
                "                            <DiscountRate>80</DiscountRate>\n" +
                "                            <DiscountRateExp>80</DiscountRateExp>\n" +
                "                            <InfantPrice>170</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>5</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>4</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>1240</AdultPrice>\n" +
                "                            <CabinAttr/>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>830</ChildiePrice>\n" +
                "                            <Code>L</Code>\n" +
                "                            <CommissionHistoryId>1679695708</CommissionHistoryId>\n" +
                "                            <DiscountRate>75</DiscountRate>\n" +
                "                            <DiscountRateExp>75</DiscountRateExp>\n" +
                "                            <InfantPrice>170</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>4</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>1160</AdultPrice>\n" +
                "                            <CabinAttr/>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>830</ChildiePrice>\n" +
                "                            <Code>M</Code>\n" +
                "                            <CommissionHistoryId>1679695708</CommissionHistoryId>\n" +
                "                            <DiscountRate>70</DiscountRate>\n" +
                "                            <DiscountRateExp>70</DiscountRateExp>\n" +
                "                            <InfantPrice>170</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>4</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>1070</AdultPrice>\n" +
                "                            <CabinAttr/>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>830</ChildiePrice>\n" +
                "                            <Code>N</Code>\n" +
                "                            <CommissionHistoryId>1679695708</CommissionHistoryId>\n" +
                "                            <DiscountRate>65</DiscountRate>\n" +
                "                            <DiscountRateExp>65</DiscountRateExp>\n" +
                "                            <InfantPrice>170</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>4</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>990</AdultPrice>\n" +
                "                            <CabinAttr/>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>830</ChildiePrice>\n" +
                "                            <Code>R</Code>\n" +
                "                            <CommissionHistoryId>1679695708</CommissionHistoryId>\n" +
                "                            <DiscountRate>60</DiscountRate>\n" +
                "                            <DiscountRateExp>60</DiscountRateExp>\n" +
                "                            <InfantPrice>170</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>4</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>910</AdultPrice>\n" +
                "                            <CabinAttr/>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>830</ChildiePrice>\n" +
                "                            <Code>S</Code>\n" +
                "                            <CommissionHistoryId>1679695708</CommissionHistoryId>\n" +
                "                            <DiscountRate>55</DiscountRate>\n" +
                "                            <DiscountRateExp>55</DiscountRateExp>\n" +
                "                            <InfantPrice>170</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>4</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                        <Cabin>\n" +
                "                            <ExtensionData/>\n" +
                "                            <AdultPrice>830</AdultPrice>\n" +
                "                            <CabinAttr/>\n" +
                "                            <CabinDesc>0</CabinDesc>\n" +
                "                            <CabinType>Y</CabinType>\n" +
                "                            <ChildiePrice>830</ChildiePrice>\n" +
                "                            <Code>V</Code>\n" +
                "                            <CommissionHistoryId>1679695708</CommissionHistoryId>\n" +
                "                            <DiscountRate>50</DiscountRate>\n" +
                "                            <DiscountRateExp>50</DiscountRateExp>\n" +
                "                            <InfantPrice>170</InfantPrice>\n" +
                "                            <IsApply>false</IsApply>\n" +
                "                            <Number>10</Number>\n" +
                "                            <PolicyType>0</PolicyType>\n" +
                "                            <RebateRate>4</RebateRate>\n" +
                "                            <Rules/>\n" +
                "                            <SpecialOfferId>-1</SpecialOfferId>\n" +
                "                            <SpecialOfferTicketType>Null</SpecialOfferTicketType>\n" +
                "                        </Cabin>\n" +
                "                    </Cabins>\n" +
                "                    <CodeShare>false</CodeShare>\n" +
                "                    <DelayPercent>86.67</DelayPercent>\n" +
                "                    <Distance>0</Distance>\n" +
                "                    <DstAirport>LXA</DstAirport>\n" +
                "                    <DstDateTime>2013-01-23T14:45:00</DstDateTime>\n" +
                "                    <DstTerm>--</DstTerm>\n" +
                "                    <FlightId>1</FlightId>\n" +
                "                    <FlightNo>MU2335</FlightNo>\n" +
                "                    <FuelTax>130</FuelTax>\n" +
                "                    <HasMeal>true</HasMeal>\n" +
                "                    <IsETkt>true</IsETkt>\n" +
                "                    <MealCode>L</MealCode>\n" +
                "                    <NextFlightId>0</NextFlightId>\n" +
                "                    <NoneDirectLine>false</NoneDirectLine>\n" +
                "                    <OpenCabinsCode>F,Y,K,B,E,H,L,M,N,R,S,V,</OpenCabinsCode>\n" +
                "                    <OrgAirport>XIY</OrgAirport>\n" +
                "                    <OrgDateTime>2013-01-23T11:35:00</OrgDateTime>\n" +
                "                    <OrgTerm>T3</OrgTerm>\n" +
                "                    <PlaneStyle>319</PlaneStyle>\n" +
                "                    <StopNumber>0</StopNumber>\n" +
                "                </AirItem>\n" +
                "            </AirItems>\n" +
                "            <Distance>1980</Distance>\n" +
                "            <DstCity>LXA</DstCity>\n" +
                "            <OrgCity>XIY</OrgCity>\n" +
                "            <OrgDate>2013-01-23T00:00:00</OrgDate>\n" +
                "        </Lines>\n" +
                "    </LinesCollection>\n" +
                "</FlightSearchReply>";
        TicketQueryResponse ticketQueryResponse = (TicketQueryResponse) parser.parse(content, TicketQueryResponse.class);
//        TicketQueryResponse ticketQueryResponse = xmlMapper.readValue(content, TicketQueryResponse.class);
        List<AirLine> airLines = ticketQueryResponse.getLinesCollection().getLines().getAirLines();
        assertThat(airLines.size(), is(1));
        assertThat(airLines.get(0).getDstAirport(), is("LXA"));
    }
}
